[package]
name = "rustmigrationspsqlroot"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.51", features = ["derive"] }
diesel = { version = "2.3.3", features = ["chrono", "postgres"] }
dotenv = "0.15.0"
